version: '3'

services:
  webserver:
    container_name: webserver
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=127.0.0.1
      PHP_IDE_CONFIG: serverName=localhost
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./:/var/www
    links:
      - db

    depends_on:
      - db

  db:
    container_name: mysql
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task-tracker
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    volumes:
      - ./docker/database:/var/lib/mysql